//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuiPuiCapaDeInterfazBackOffice.LogicaClaseSalon {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LogicaClaseSalon.FachadaClaseSalonBackOfficeSoap")]
    public interface FachadaClaseSalonBackOfficeSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioConsultarClaseSalonTodos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ServicioConsultarClaseSalonTodos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioConsultarClaseSalonTodos", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ServicioConsultarClaseSalonTodosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioConsultarPorClase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ServicioConsultarPorClase(string clase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioConsultarPorClase", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ServicioConsultarPorClaseAsync(string clase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioConsultarPorSalon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ServicioConsultarPorSalon(string salon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioConsultarPorSalon", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ServicioConsultarPorSalonAsync(string salon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioConsultarPorInstructor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ServicioConsultarPorInstructor(string instructor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioConsultarPorInstructor", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ServicioConsultarPorInstructorAsync(string instructor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioInsertarClaseSalon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ServicioInsertarClaseSalon(int id, int id_clase, int id_salon, int id_instructor, int id_horario, int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioInsertarClaseSalon", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ServicioInsertarClaseSalonAsync(int id, int id_clase, int id_salon, int id_instructor, int id_horario, int status);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FachadaClaseSalonBackOfficeSoapChannel : PuiPuiCapaDeInterfazBackOffice.LogicaClaseSalon.FachadaClaseSalonBackOfficeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FachadaClaseSalonBackOfficeSoapClient : System.ServiceModel.ClientBase<PuiPuiCapaDeInterfazBackOffice.LogicaClaseSalon.FachadaClaseSalonBackOfficeSoap>, PuiPuiCapaDeInterfazBackOffice.LogicaClaseSalon.FachadaClaseSalonBackOfficeSoap {
        
        public FachadaClaseSalonBackOfficeSoapClient() {
        }
        
        public FachadaClaseSalonBackOfficeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FachadaClaseSalonBackOfficeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FachadaClaseSalonBackOfficeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FachadaClaseSalonBackOfficeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ServicioConsultarClaseSalonTodos() {
            return base.Channel.ServicioConsultarClaseSalonTodos();
        }
        
        public System.Threading.Tasks.Task<string> ServicioConsultarClaseSalonTodosAsync() {
            return base.Channel.ServicioConsultarClaseSalonTodosAsync();
        }
        
        public string ServicioConsultarPorClase(string clase) {
            return base.Channel.ServicioConsultarPorClase(clase);
        }
        
        public System.Threading.Tasks.Task<string> ServicioConsultarPorClaseAsync(string clase) {
            return base.Channel.ServicioConsultarPorClaseAsync(clase);
        }
        
        public string ServicioConsultarPorSalon(string salon) {
            return base.Channel.ServicioConsultarPorSalon(salon);
        }
        
        public System.Threading.Tasks.Task<string> ServicioConsultarPorSalonAsync(string salon) {
            return base.Channel.ServicioConsultarPorSalonAsync(salon);
        }
        
        public string ServicioConsultarPorInstructor(string instructor) {
            return base.Channel.ServicioConsultarPorInstructor(instructor);
        }
        
        public System.Threading.Tasks.Task<string> ServicioConsultarPorInstructorAsync(string instructor) {
            return base.Channel.ServicioConsultarPorInstructorAsync(instructor);
        }
        
        public int ServicioInsertarClaseSalon(int id, int id_clase, int id_salon, int id_instructor, int id_horario, int status) {
            return base.Channel.ServicioInsertarClaseSalon(id, id_clase, id_salon, id_instructor, id_horario, status);
        }
        
        public System.Threading.Tasks.Task<int> ServicioInsertarClaseSalonAsync(int id, int id_clase, int id_salon, int id_instructor, int id_horario, int status) {
            return base.Channel.ServicioInsertarClaseSalonAsync(id, id_clase, id_salon, id_instructor, id_horario, status);
        }
    }
}
