//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuiPuiCapaDeInterfazFrontOffice.FachadaInstructoresFrontOffice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FachadaInstructoresFrontOffice.FachadaInstructoresSoap")]
    public interface FachadaInstructoresSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioComandoConsultarEvaluacionesInstructorTodos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ServicioComandoConsultarEvaluacionesInstructorTodos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioComandoConsultarEvaluacionesInstructorTodos", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ServicioComandoConsultarEvaluacionesInstructorTodosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioComandoConsultarEvaluacionesInstructorDetalle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ServicioComandoConsultarEvaluacionesInstructorDetalle(int id_evaluacion_instructor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioComandoConsultarEvaluacionesInstructorDetalle", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ServicioComandoConsultarEvaluacionesInstructorDetalleAsync(int id_evaluacion_instructor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioComandoInsertarEvaluacionesInstructor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ServicioComandoInsertarEvaluacionesInstructor(System.DateTime fecha, string observaciones, int status, string idcliente, string idinstructor, int calificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioComandoInsertarEvaluacionesInstructor", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ServicioComandoInsertarEvaluacionesInstructorAsync(System.DateTime fecha, string observaciones, int status, string idcliente, string idinstructor, int calificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioComandoModificarEvaluacionesInstructor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ServicioComandoModificarEvaluacionesInstructor(int id, System.DateTime fecha, string observaciones, int status, string idcliente, string idinstructor, int calificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioComandoModificarEvaluacionesInstructor", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ServicioComandoModificarEvaluacionesInstructorAsync(int id, System.DateTime fecha, string observaciones, int status, string idcliente, string idinstructor, int calificacion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FachadaInstructoresSoapChannel : PuiPuiCapaDeInterfazFrontOffice.FachadaInstructoresFrontOffice.FachadaInstructoresSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FachadaInstructoresSoapClient : System.ServiceModel.ClientBase<PuiPuiCapaDeInterfazFrontOffice.FachadaInstructoresFrontOffice.FachadaInstructoresSoap>, PuiPuiCapaDeInterfazFrontOffice.FachadaInstructoresFrontOffice.FachadaInstructoresSoap {
        
        public FachadaInstructoresSoapClient() {
        }
        
        public FachadaInstructoresSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FachadaInstructoresSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FachadaInstructoresSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FachadaInstructoresSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ServicioComandoConsultarEvaluacionesInstructorTodos() {
            return base.Channel.ServicioComandoConsultarEvaluacionesInstructorTodos();
        }
        
        public System.Threading.Tasks.Task<string> ServicioComandoConsultarEvaluacionesInstructorTodosAsync() {
            return base.Channel.ServicioComandoConsultarEvaluacionesInstructorTodosAsync();
        }
        
        public string ServicioComandoConsultarEvaluacionesInstructorDetalle(int id_evaluacion_instructor) {
            return base.Channel.ServicioComandoConsultarEvaluacionesInstructorDetalle(id_evaluacion_instructor);
        }
        
        public System.Threading.Tasks.Task<string> ServicioComandoConsultarEvaluacionesInstructorDetalleAsync(int id_evaluacion_instructor) {
            return base.Channel.ServicioComandoConsultarEvaluacionesInstructorDetalleAsync(id_evaluacion_instructor);
        }
        
        public int ServicioComandoInsertarEvaluacionesInstructor(System.DateTime fecha, string observaciones, int status, string idcliente, string idinstructor, int calificacion) {
            return base.Channel.ServicioComandoInsertarEvaluacionesInstructor(fecha, observaciones, status, idcliente, idinstructor, calificacion);
        }
        
        public System.Threading.Tasks.Task<int> ServicioComandoInsertarEvaluacionesInstructorAsync(System.DateTime fecha, string observaciones, int status, string idcliente, string idinstructor, int calificacion) {
            return base.Channel.ServicioComandoInsertarEvaluacionesInstructorAsync(fecha, observaciones, status, idcliente, idinstructor, calificacion);
        }
        
        public bool ServicioComandoModificarEvaluacionesInstructor(int id, System.DateTime fecha, string observaciones, int status, string idcliente, string idinstructor, int calificacion) {
            return base.Channel.ServicioComandoModificarEvaluacionesInstructor(id, fecha, observaciones, status, idcliente, idinstructor, calificacion);
        }
        
        public System.Threading.Tasks.Task<bool> ServicioComandoModificarEvaluacionesInstructorAsync(int id, System.DateTime fecha, string observaciones, int status, string idcliente, string idinstructor, int calificacion) {
            return base.Channel.ServicioComandoModificarEvaluacionesInstructorAsync(id, fecha, observaciones, status, idcliente, idinstructor, calificacion);
        }
    }
}
