//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18047.
// 
#pragma warning disable 1591

namespace PuiPuiCapaDeInterfazFrontOffice.LogicaReservarClase {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FachadaReservarClasesFrontOfficeSoap", Namespace="http://tempuri.org/")]
    public partial class FachadaReservarClasesFrontOffice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ServicioConsultarTodosReservacionesClasesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ServicioConsultarDetalleReservacionPorIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FachadaReservarClasesFrontOffice() {
            this.Url = global::PuiPuiCapaDeInterfazFrontOffice.Properties.Settings.Default.PuiPuiCapaDeInterfazFrontOffice_LogicaReservarClase_FachadaReservarClasesFrontOffice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ServicioConsultarTodosReservacionesClasesCompletedEventHandler ServicioConsultarTodosReservacionesClasesCompleted;
        
        /// <remarks/>
        public event ServicioConsultarDetalleReservacionPorIdCompletedEventHandler ServicioConsultarDetalleReservacionPorIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ServicioConsultarTodosReservacionesClases", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ServicioConsultarTodosReservacionesClases() {
            object[] results = this.Invoke("ServicioConsultarTodosReservacionesClases", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ServicioConsultarTodosReservacionesClasesAsync() {
            this.ServicioConsultarTodosReservacionesClasesAsync(null);
        }
        
        /// <remarks/>
        public void ServicioConsultarTodosReservacionesClasesAsync(object userState) {
            if ((this.ServicioConsultarTodosReservacionesClasesOperationCompleted == null)) {
                this.ServicioConsultarTodosReservacionesClasesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnServicioConsultarTodosReservacionesClasesOperationCompleted);
            }
            this.InvokeAsync("ServicioConsultarTodosReservacionesClases", new object[0], this.ServicioConsultarTodosReservacionesClasesOperationCompleted, userState);
        }
        
        private void OnServicioConsultarTodosReservacionesClasesOperationCompleted(object arg) {
            if ((this.ServicioConsultarTodosReservacionesClasesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ServicioConsultarTodosReservacionesClasesCompleted(this, new ServicioConsultarTodosReservacionesClasesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ServicioConsultarDetalleReservacionPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ServicioConsultarDetalleReservacionPorId(int idReservacion) {
            object[] results = this.Invoke("ServicioConsultarDetalleReservacionPorId", new object[] {
                        idReservacion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ServicioConsultarDetalleReservacionPorIdAsync(int idReservacion) {
            this.ServicioConsultarDetalleReservacionPorIdAsync(idReservacion, null);
        }
        
        /// <remarks/>
        public void ServicioConsultarDetalleReservacionPorIdAsync(int idReservacion, object userState) {
            if ((this.ServicioConsultarDetalleReservacionPorIdOperationCompleted == null)) {
                this.ServicioConsultarDetalleReservacionPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnServicioConsultarDetalleReservacionPorIdOperationCompleted);
            }
            this.InvokeAsync("ServicioConsultarDetalleReservacionPorId", new object[] {
                        idReservacion}, this.ServicioConsultarDetalleReservacionPorIdOperationCompleted, userState);
        }
        
        private void OnServicioConsultarDetalleReservacionPorIdOperationCompleted(object arg) {
            if ((this.ServicioConsultarDetalleReservacionPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ServicioConsultarDetalleReservacionPorIdCompleted(this, new ServicioConsultarDetalleReservacionPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ServicioConsultarTodosReservacionesClasesCompletedEventHandler(object sender, ServicioConsultarTodosReservacionesClasesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServicioConsultarTodosReservacionesClasesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ServicioConsultarTodosReservacionesClasesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ServicioConsultarDetalleReservacionPorIdCompletedEventHandler(object sender, ServicioConsultarDetalleReservacionPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServicioConsultarDetalleReservacionPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ServicioConsultarDetalleReservacionPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591