//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuiPuiCapaDeInterfazBackOffice.LogicaClase {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LogicaClase.FachadaClasesSoap")]
    public interface FachadaClasesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioConsultarSalonesTodos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ServicioConsultarSalonesTodos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioConsultarSalonesTodos", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ServicioConsultarSalonesTodosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioAgregarClase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ServicioAgregarClase(string nombre, int idClase, string descripcion, int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioAgregarClase", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ServicioAgregarClaseAsync(string nombre, int idClase, string descripcion, int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioInactivarClase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ServicioInactivarClase(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioInactivarClase", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ServicioInactivarClaseAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioModificarClase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ServicioModificarClase(int id, string nombre, int idClase, string descripcion, int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioModificarClase", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ServicioModificarClaseAsync(int id, string nombre, int idClase, string descripcion, int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioComandoNombreClase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ServicioComandoNombreClase(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioComandoNombreClase", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ServicioComandoNombreClaseAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioComandoBusquedaStatusClases", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ServicioComandoBusquedaStatusClases(int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioComandoBusquedaStatusClases", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ServicioComandoBusquedaStatusClasesAsync(int status);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FachadaClasesSoapChannel : PuiPuiCapaDeInterfazBackOffice.LogicaClase.FachadaClasesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FachadaClasesSoapClient : System.ServiceModel.ClientBase<PuiPuiCapaDeInterfazBackOffice.LogicaClase.FachadaClasesSoap>, PuiPuiCapaDeInterfazBackOffice.LogicaClase.FachadaClasesSoap {
        
        public FachadaClasesSoapClient() {
        }
        
        public FachadaClasesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FachadaClasesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FachadaClasesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FachadaClasesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ServicioConsultarSalonesTodos() {
            return base.Channel.ServicioConsultarSalonesTodos();
        }
        
        public System.Threading.Tasks.Task<string> ServicioConsultarSalonesTodosAsync() {
            return base.Channel.ServicioConsultarSalonesTodosAsync();
        }
        
        public int ServicioAgregarClase(string nombre, int idClase, string descripcion, int status) {
            return base.Channel.ServicioAgregarClase(nombre, idClase, descripcion, status);
        }
        
        public System.Threading.Tasks.Task<int> ServicioAgregarClaseAsync(string nombre, int idClase, string descripcion, int status) {
            return base.Channel.ServicioAgregarClaseAsync(nombre, idClase, descripcion, status);
        }
        
        public bool ServicioInactivarClase(int id) {
            return base.Channel.ServicioInactivarClase(id);
        }
        
        public System.Threading.Tasks.Task<bool> ServicioInactivarClaseAsync(int id) {
            return base.Channel.ServicioInactivarClaseAsync(id);
        }
        
        public bool ServicioModificarClase(int id, string nombre, int idClase, string descripcion, int status) {
            return base.Channel.ServicioModificarClase(id, nombre, idClase, descripcion, status);
        }
        
        public System.Threading.Tasks.Task<bool> ServicioModificarClaseAsync(int id, string nombre, int idClase, string descripcion, int status) {
            return base.Channel.ServicioModificarClaseAsync(id, nombre, idClase, descripcion, status);
        }
        
        public string ServicioComandoNombreClase(string nombre) {
            return base.Channel.ServicioComandoNombreClase(nombre);
        }
        
        public System.Threading.Tasks.Task<string> ServicioComandoNombreClaseAsync(string nombre) {
            return base.Channel.ServicioComandoNombreClaseAsync(nombre);
        }
        
        public string ServicioComandoBusquedaStatusClases(int status) {
            return base.Channel.ServicioComandoBusquedaStatusClases(status);
        }
        
        public System.Threading.Tasks.Task<string> ServicioComandoBusquedaStatusClasesAsync(int status) {
            return base.Channel.ServicioComandoBusquedaStatusClasesAsync(status);
        }
    }
}
