//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18047
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuiPuiCapaDeInterfazBackOffice.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:24057/Servicios/BackOffice/FachadaClasesBackOffice.asmx")]
        public string PuiPuiCapaDeInterfazBackOffice_LogicaClases_FachadaClases {
            get {
                return ((string)(this["PuiPuiCapaDeInterfazBackOffice_LogicaClases_FachadaClases"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:24057/Servicios/BackOffice/FachadaEjerciciosBackOffice.asmx")]
        public string PuiPuiCapaDeInterfazBackOffice_LogicaEjercicios_FachadaEjerciciosBackOffice {
            get {
                return ((string)(this["PuiPuiCapaDeInterfazBackOffice_LogicaEjercicios_FachadaEjerciciosBackOffice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:24057/Servicios/BackOffice/FachadaInstructoresBackOffice.asmx")]
        public string PuiPuiCapaDeInterfazBackOffice_LogicaPersonas_FachadaPersonas {
            get {
                return ((string)(this["PuiPuiCapaDeInterfazBackOffice_LogicaPersonas_FachadaPersonas"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:24057/Servicios/BackOffice/FachadaUsuariosLoginBackOffice.asmx")]
        public string PuiPuiCapaDeInterfazBackOffice_LogicaUsuariosLogin_FachadaUsuariosLogin {
            get {
                return ((string)(this["PuiPuiCapaDeInterfazBackOffice_LogicaUsuariosLogin_FachadaUsuariosLogin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:24057/Servicios/BackOffice/FachadaMusculos.asmx")]
        public string PuiPuiCapaDeInterfazBackOffice_localhost_FachadaMusculos {
            get {
                return ((string)(this["PuiPuiCapaDeInterfazBackOffice_localhost_FachadaMusculos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:24057/Servicios/BackOffice/FachadaMusculos.asmx")]
        public string PuiPuiCapaDeInterfazBackOffice_LogicaMusculo_FachadaMusculos {
            get {
                return ((string)(this["PuiPuiCapaDeInterfazBackOffice_LogicaMusculo_FachadaMusculos"]));
            }
        }
    }
}
