//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuiPuiCapaDeInterfazFrontOffice.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:24057/Servicios/FrontOffice/FachadaClasesFrontOffice.asmx")]
        public string PuiPuiCapaDeInterfazFrontOffice_LogicaClases_FachadaClases {
            get {
                return ((string)(this["PuiPuiCapaDeInterfazFrontOffice_LogicaClases_FachadaClases"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:24057/Servicios/FrontOffice/FachadaEjerciciosFrontOffice.asmx")]
        public string PuiPuiCapaDeInterfazFrontOffice_LogicaEjercicios_FachadaEjercicios {
            get {
                return ((string)(this["PuiPuiCapaDeInterfazFrontOffice_LogicaEjercicios_FachadaEjercicios"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:24057/Servicios/FrontOffice/FachadaInstructoresFrontOffice.asmx")]
        public string PuiPuiCapaDeInterfazFrontOffice_LogicaInstructores_FachadaInstructores {
            get {
                return ((string)(this["PuiPuiCapaDeInterfazFrontOffice_LogicaInstructores_FachadaInstructores"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:24057/Servicios/FrontOffice/FachadaRutinasEjerciciosFrontOffice." +
            "asmx")]
        public string PuiPuiCapaDeInterfazFrontOffice_LogicaRutinasEjercicios_FachadaRutinasEjercicios {
            get {
                return ((string)(this["PuiPuiCapaDeInterfazFrontOffice_LogicaRutinasEjercicios_FachadaRutinasEjercicios"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:24057/Servicios/FrontOffice/FachadaUsuariosLoginFrontOffice.asmx" +
            "")]
        public string PuiPuiCapaDeInterfazFrontOffice_LogicaUsuariosLogin_FachadaClientes {
            get {
                return ((string)(this["PuiPuiCapaDeInterfazFrontOffice_LogicaUsuariosLogin_FachadaClientes"]));
            }
        }
    }
}
