//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuiPui_FrontOffice.Presentacion.Vista.Modulo5
{


    public partial class Modulo5
    {
    }
}
